# Generated by Django 5.0.3 on 2024-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ARTIST', 'Artist'), ('BUYER', 'Buyer')], default='ARTIST', max_length=10, null=True),
        ),
    ]
