# Generated by Django 5.2.5 on 2026-02-22 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_account_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('ARTIST', 'artist'), ('CLUB', 'club'), ('UND', 'und')], default='ARTIST', max_length=20),
        ),
    ]
