# Generated by Django 5.2.5 on 2026-07-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_alter_account_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("es", "Español"), ("fr", "Français")],
                default="en",
                max_length=2,
            ),
        ),
    ]
