# Generated by Django 5.2.5 on 2026-02-21 03:22

import legal.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0010_remove_mastersplit_legal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitsheet',
            name='track_cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='acrylic-static-dev'), upload_to=legal.models.get_upload_path),
        ),
    ]
