# Generated by Django 5.2.5 on 2026-06-08 17:49

import legal.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0011_alter_splitsheet_track_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitsheet',
            name='track_cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name=''), upload_to=legal.models.get_upload_path),
        ),
    ]
