# Generated by Django 5.2.5 on 2026-06-15 21:42

import common.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_alter_track_aims_status_alter_track_file_wav'),
        ('club', '0006_club_country'),
        ('legal', '0011_alter_splitsheet_track_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], db_index=True, default='IN_PROGRESS', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='club.club')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_licenses', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='catalog.track')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LicenseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_status_changes', to=settings.AUTH_USER_MODEL)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='legal.license')),
            ],
            options={
                'ordering': ['-changed_at', '-created'],
            },
        ),
        migrations.AddIndex(
            model_name='license',
            index=common.models.PostgresIndex(fields=['uuid'], name='legal_license_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=common.models.PostgresIndex(fields=['created'], name='legal_license_created_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=common.models.PostgresIndex(fields=['updated'], name='legal_license_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['club', 'status'], name='legal_licen_club_id_911ab0_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['track', 'status'], name='legal_licen_track_i_362b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['starts_at'], name='legal_licen_starts__fd32f9_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['ends_at'], name='legal_licen_ends_at_a4ea18_idx'),
        ),
        migrations.AddIndex(
            model_name='licensehistory',
            index=common.models.PostgresIndex(fields=['uuid'], name='legal_licensehistory_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='licensehistory',
            index=common.models.PostgresIndex(fields=['created'], name='legal_licensehistory_created_idx'),
        ),
        migrations.AddIndex(
            model_name='licensehistory',
            index=common.models.PostgresIndex(fields=['updated'], name='legal_licensehistory_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='licensehistory',
            index=models.Index(fields=['license', 'changed_at'], name='legal_licen_license_afdcf7_idx'),
        ),
        migrations.AddIndex(
            model_name='licensehistory',
            index=models.Index(fields=['to_status'], name='legal_licen_to_stat_9d4516_idx'),
        ),
    ]
