# Generated by Django 5.2.5 on 2026-02-21 03:22

import catalog.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_genre_catalog_genre_uuid_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclist',
            name='background_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='acrylic-static-dev'), upload_to=catalog.models.get_sync_upload_path),
        ),
        migrations.AlterField(
            model_name='synclist',
            name='cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='acrylic-static-dev'), upload_to=catalog.models.get_sync_upload_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='acrylic-static-dev'), upload_to=catalog.models.get_upload_path),
        ),
    ]
