# Generated by Django 5.2.5 on 2026-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_synclist_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='aims_id',
            field=models.PositiveBigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='aims_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('success', 'success')], db_index=True, default='pending', max_length=20),
        ),
    ]
