# Generated by Django 5.2.5 on 2026-03-22 00:00

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_track_aims_id_track_aims_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='waveform',
            field=models.FileField(blank=True, upload_to=catalog.models.get_waveform_upload_path),
        ),
    ]

