# Generated by Django 5.2.5 on 2026-06-15 21:42

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_track_virality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='aims_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('success', 'success'), ('finished', 'finished')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='track',
            name='file_wav',
            field=models.FileField(blank=True, upload_to=catalog.models.get_label_audio_upload_path),
        ),
    ]
