# Generated by Django 5.2.5 on 2026-07-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="extended_commercial_use",
            field=models.BooleanField(default=False),
        ),
    ]
