# Generated by Django 5.2.5 on 2026-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
