# Generated by Django 5.2.5 on 2026-08-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_track_extended_commercial_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='archival',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='youtube_restriction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
