# Generated by Django 5.2.5 on 2026-09-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0034_track_archival_track_youtube_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
