# Generated by Django 5.2.5 on 2026-02-21 03:22

import artist.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0018_artist_isni_artist_artist_arti_isni_0bacd9_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='background_image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='acrylic-static-dev'), upload_to=artist.models.get_aritst_upload_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, storage=storages.backends.s3.S3Storage(bucket_name='acrylic-static-dev'), upload_to=artist.models.get_aritst_upload_path),
        ),
    ]
