# Generated by Django 5.2.5 on 2026-03-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0019_alter_artist_background_image_alter_artist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='chartmetric_instagram_audience_updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='chartmetric_instagram_demographics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='chartmetric_instagram_top_cities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='chartmetric_instagram_top_countries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube_followers',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
