# Generated by Codex on 2026-03-25

from django.db import migrations


def fix_empty_spotify_popularity(apps, schema_editor):
    """
    Some local SQLite DBs can end up with '' stored in integer columns (SQLite is loosely typed).
    DRF then crashes when it tries to serialize that value as an int.

    Postgres/MySQL would not allow this, so only run for SQLite.
    """
    if schema_editor.connection.vendor != "sqlite":
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "UPDATE artist_artist SET spotify_popularity = 0 "
            "WHERE spotify_popularity = '' OR spotify_popularity IS NULL"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0020_artist_chartmetric_instagram_audience_updated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(fix_empty_spotify_popularity, migrations.RunPython.noop),
    ]

