# Generated by GPT-5.2 on 2026-04-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("label", "0001_initial"),
        ("artist", "0022_artist_chartmetric_instagram_interests_and_sports_fit"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="label",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="artists",
                to="label.label",
            ),
        ),
    ]

