# Generated by Django 5.2.5 on 2026-02-25 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(condition=models.Q(('slug', ''), _negated=True), fields=('slug',), name='unique_club_slug'),
        ),
    ]
