# Generated by Django 5.2.5 on 2026-04-27 01:40

import common.models
import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_fill_missing_club_slugs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('nationality', django_countries.fields.CountryField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='club.club')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='club_player_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='club_player_created_idx'), common.models.PostgresIndex(fields=['updated'], name='club_player_updated_idx'), models.Index(fields=['club', 'name'], name='club_player_club_id_8f73c5_idx')],
            },
        ),
    ]
