# Generated by Django 5.2.5 on 2026-04-30 05:21

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
