# Generated by Django 5.2.5 on 2026-06-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0006_club_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="club",
            name="other_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="club",
            name="tiktok_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="club",
            name="youtube_url",
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
