# Generated by Django 5.2.5 on 2026-07-06 22:49

import common.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_initial'),
        ('club', '0007_club_social_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='other_url',
        ),
        migrations.AlterField(
            model_name='club',
            name='instagram_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.CreateModel(
            name='TrackFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_favorites', to='club.club')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_favorites', to='catalog.track')),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [common.models.PostgresIndex(fields=['uuid'], name='club_trackfavorite_uuid_idx'), common.models.PostgresIndex(fields=['created'], name='club_trackfavorite_created_idx'), common.models.PostgresIndex(fields=['updated'], name='club_trackfavorite_updated_idx'), models.Index(fields=['club', 'track'], name='club_trackf_club_id_ecd864_idx')],
                'constraints': [models.UniqueConstraint(fields=('club', 'track'), name='unique_club_track_favorite')],
            },
        ),
    ]
