# Generated by Django 5.2.5 on 2026-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_social_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='instagram_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='youtube_url',
            field=models.URLField(blank=True, default='', max_length=255),
        ),
    ]
