# Generated by Django 5.2.5 on 2026-07-14 17:50

import content.models
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                storage=storages.backends.s3.S3Storage(
                    bucket_name="acrylic-static-dev"
                ),
                upload_to=content.models.get_sync_upload_path,
            ),
        ),
    ]
