# Generated by Codex for AIMS video multipart uploads.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AimsVideoMultipartUpload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("s3_key", models.CharField(max_length=1024)),
                ("s3_upload_id", models.TextField()),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(default="application/octet-stream", max_length=127)),
                ("size_bytes", models.BigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("completed", "Completed"),
                            ("processing", "Processing"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                            ("aborted", "Aborted"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                ("aims_hash", models.CharField(blank=True, max_length=255)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aims_video_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aimsvideomultipartupload",
            index=models.Index(fields=["user", "status"], name="aims_aimsvi_user_id_b11602_idx"),
        ),
        migrations.AddIndex(
            model_name="aimsvideomultipartupload",
            index=models.Index(fields=["uuid"], name="aims_aimsvi_uuid_655b91_idx"),
        ),
        migrations.AddIndex(
            model_name="aimsvideomultipartupload",
            index=models.Index(fields=["created_at"], name="aims_aimsvi_created_5ec3a0_idx"),
        ),
    ]
