# Generated by Django 5.2.5 on 2026-07-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aims", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="aimsvideomultipartupload",
            new_name="aims_aimsvi_user_id_09f803_idx",
            old_name="aims_aimsvi_user_id_b11602_idx",
        ),
        migrations.RenameIndex(
            model_name="aimsvideomultipartupload",
            new_name="aims_aimsvi_uuid_a4c194_idx",
            old_name="aims_aimsvi_uuid_655b91_idx",
        ),
        migrations.RenameIndex(
            model_name="aimsvideomultipartupload",
            new_name="aims_aimsvi_created_a20410_idx",
            old_name="aims_aimsvi_created_5ec3a0_idx",
        ),
    ]
