# Generated by Django 5.2.5 on 2026-06-17 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0002_buyer"),
        ("catalog", "0032_initial"),
        ("club", "0007_club_social_urls"),
        ("license", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extended_commercial_use", models.BooleanField(default=False)),
                ("selected_platforms", models.JSONField(default=list)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_error", models.TextField(blank=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="club.club",
                    ),
                ),
                (
                    "tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to="buyer.tier",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="catalog.track",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelist Request",
                "verbose_name_plural": "Whitelist Requests",
                "ordering": ["-created"],
            },
        ),
        migrations.DeleteModel(
            name="WhitelistRequest",
        ),
        migrations.AddConstraint(
            model_name="license",
            constraint=models.UniqueConstraint(
                fields=("club", "track"), name="unique_license_club_track"
            ),
        ),
    ]
