# Generated by Django 5.2.5 on 2026-06-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0002_rename_to_license_and_add_extended_commercial_use'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-created'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.RemoveField(
            model_name='license',
            name='extended_commercial_use',
        ),
        migrations.RemoveField(
            model_name='license',
            name='selected_platforms',
        ),
        migrations.RemoveField(
            model_name='license',
            name='tier',
        ),
    ]
