# Generated by Django 5.2.5 on 2026-07-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_license_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='license',
            name='ecu_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='license',
            name='extended_commercial_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='license',
            name='tier',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
