# Generated by Django 5.2.5 on 2026-09-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license', '0003_alter_license_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='license',
            name='downloaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
